#!/usr/bin/env python3
"""Materializa os gabaritos v1.2; cada consulta fixa UTC e ordenação estável."""
from pathlib import Path

P = Path(__file__).parent
q = {
1: "SELECT categoria_id,nome,ativa FROM categorias WHERE ativa ORDER BY nome,categoria_id;",
2: "SELECT produto_id,sku,nome,preco_lista_atual FROM produtos WHERE preco_lista_atual BETWEEN 50.00 AND 100.00 ORDER BY preco_lista_atual,sku;",
3: "SELECT produto_id,sku,nome,data_descontinuacao FROM produtos WHERE data_descontinuacao IS NOT NULL ORDER BY data_descontinuacao,sku;",
4: "SELECT regiao,count(*) clientes FROM clientes GROUP BY regiao ORDER BY regiao;",
5: "SELECT count(data_nascimento) clientes_com_data_nascimento FROM clientes;",
6: "SELECT pedido_id,numero_pedido,(data_pedido AT TIME ZONE 'America/Sao_Paulo')::date data_pedido_civil FROM pedidos WHERE cliente_id IS NULL ORDER BY data_pedido,pedido_id;",
7: "SELECT extract(year FROM data_pedido AT TIME ZONE 'America/Sao_Paulo')::int ano,count(*) pedidos FROM pedidos GROUP BY 1 ORDER BY 1;",
8: "SELECT min(preco_lista_atual) preco_minimo,max(preco_lista_atual) preco_maximo,avg(preco_lista_atual) preco_medio FROM produtos;",
9: "SELECT produto_id,sku,nome,preco_lista_atual FROM produtos WHERE ativo ORDER BY preco_lista_atual DESC,sku LIMIT 10;",
10: "SELECT status_logistico,count(*) pedidos FROM pedidos GROUP BY 1 ORDER BY 1;",
11: "SELECT i.item_pedido_id,i.pedido_id,i.numero_item,i.produto_id,i.quantidade,i.preco_unitario,i.quantidade*i.preco_unitario valor_bruto_item FROM itens_pedido i ORDER BY i.pedido_id,i.numero_item;",
12: "SELECT p.pedido_id,p.numero_pedido,sum(i.quantidade*(i.preco_unitario-i.desconto_unitario)) receita_mercadoria_liquida FROM pedidos p JOIN itens_pedido i USING(pedido_id) WHERE p.status_logistico<>'CANCELADO' GROUP BY p.pedido_id,p.numero_pedido ORDER BY p.numero_pedido;",
13: "SELECT p.pedido_id,p.numero_pedido,sum(i.quantidade*i.desconto_unitario) desconto_mercadoria FROM pedidos p JOIN itens_pedido i USING(pedido_id) WHERE p.status_logistico<>'CANCELADO' GROUP BY p.pedido_id,p.numero_pedido ORDER BY p.numero_pedido;",
14: "SELECT date_trunc('month',p.data_pedido AT TIME ZONE 'America/Sao_Paulo')::date mes,sum(v.receita_mercadoria_pre_devolucao) receita_mercadoria_liquida FROM vw_itens_venda v JOIN pedidos p USING(pedido_id) WHERE v.elegivel GROUP BY 1 ORDER BY 1;",
15: "SELECT c.canal_id,c.codigo,c.nome,count(m.pedido_id) pedidos,coalesce(sum(m.receita_mercadoria_pre_devolucao),0) receita_mercadoria_liquida FROM canais c LEFT JOIN vw_pedidos_metricas m ON m.canal_id=c.canal_id AND m.status_logistico<>'CANCELADO' GROUP BY c.canal_id,c.codigo,c.nome ORDER BY c.codigo;",
16: "SELECT c.canal_id,c.codigo,c.nome,count(m.pedido_id) pedidos,coalesce(sum(m.receita_mercadoria_pre_devolucao),0) receita_mercadoria_liquida,coalesce(sum(m.receita_mercadoria_pre_devolucao),0)/nullif(count(m.pedido_id),0) ticket_medio FROM canais c LEFT JOIN vw_pedidos_metricas m ON m.canal_id=c.canal_id AND m.status_logistico<>'CANCELADO' GROUP BY c.canal_id,c.codigo,c.nome ORDER BY c.codigo;",
17: "SELECT c.categoria_id,c.nome categoria,coalesce(sum(v.receita_mercadoria_pre_devolucao),0) receita_mercadoria_liquida FROM categorias c LEFT JOIN produtos r USING(categoria_id) LEFT JOIN vw_itens_venda v ON v.produto_id=r.produto_id AND v.elegivel GROUP BY c.categoria_id,c.nome ORDER BY receita_mercadoria_liquida DESC,c.nome;",
18: "SELECT r.produto_id,r.sku,r.nome FROM produtos r WHERE NOT EXISTS (SELECT 1 FROM itens_pedido i JOIN pedidos p USING(pedido_id) WHERE i.produto_id=r.produto_id AND p.status_logistico<>'CANCELADO') ORDER BY r.sku;",
19: "SELECT c.cliente_id,c.codigo_cliente,c.nome FROM clientes c WHERE NOT EXISTS (SELECT 1 FROM pedidos p WHERE p.cliente_id=c.cliente_id AND p.status_logistico<>'CANCELADO') ORDER BY c.codigo_cliente;",
20: "SELECT v.vendedor_id,v.matricula,v.nome,v.equipe FROM vendedores v WHERE NOT EXISTS (SELECT 1 FROM pedidos p WHERE p.vendedor_id=v.vendedor_id AND p.status_logistico<>'CANCELADO') ORDER BY v.matricula;",
21: "WITH receita AS (SELECT v.vendedor_id,v.equipe,v.matricula,v.nome,coalesce(sum(m.receita_mercadoria_pre_devolucao),0) receita FROM vendedores v LEFT JOIN vw_pedidos_metricas m ON m.vendedor_id=v.vendedor_id AND m.status_logistico<>'CANCELADO' GROUP BY v.vendedor_id,v.equipe,v.matricula,v.nome), r AS (SELECT *,row_number() over(partition by equipe order by receita DESC,matricula ASC) posicao FROM receita) SELECT equipe,matricula,nome,receita,posicao FROM r WHERE posicao=1 ORDER BY equipe,matricula;",
22: "WITH x AS (SELECT c.canal_id,c.codigo,c.nome,coalesce(sum(m.receita_mercadoria_pre_devolucao),0) receita FROM canais c LEFT JOIN vw_pedidos_metricas m ON m.canal_id=c.canal_id AND m.status_logistico<>'CANCELADO' GROUP BY c.canal_id,c.codigo,c.nome), t AS (SELECT sum(receita) total FROM x) SELECT x.codigo,x.nome,x.receita,100*x.receita/nullif(t.total,0) participacao_receita_pct FROM x CROSS JOIN t ORDER BY x.codigo;",
23: "SELECT date_trunc('month',p.data_pedido AT TIME ZONE 'America/Sao_Paulo')::date mes,sum(v.desconto) desconto_mercadoria,sum(v.bruto) receita_bruta,100*sum(v.desconto)/nullif(sum(v.bruto),0) desconto_efetivo_pct FROM vw_itens_venda v JOIN pedidos p USING(pedido_id) WHERE v.elegivel GROUP BY 1 ORDER BY 1;",
24: "SELECT m.numero_pedido,count(*) FILTER(WHERE p.tipo_evento='COBRANCA' AND p.status='APROVADO') quantidade_cobrancas_aprovadas,count(DISTINCT p.meio_pagamento) FILTER(WHERE p.tipo_evento='COBRANCA' AND p.status='APROVADO') quantidade_meios,sum(p.valor) FILTER(WHERE p.tipo_evento='COBRANCA' AND p.status='APROVADO') valor_cobrado_aprovado FROM vw_pedidos_metricas m JOIN pagamentos p USING(pedido_id) WHERE m.status_logistico<>'CANCELADO' GROUP BY m.pedido_id,m.numero_pedido,m.receita_mercadoria_pre_devolucao,m.frete_cobrado_elegivel HAVING count(*) FILTER(WHERE p.tipo_evento='COBRANCA' AND p.status='APROVADO')=2 AND count(DISTINCT p.meio_pagamento) FILTER(WHERE p.tipo_evento='COBRANCA' AND p.status='APROVADO')=2 AND sum(p.valor) FILTER(WHERE p.tipo_evento='COBRANCA' AND p.status='APROVADO')=m.receita_mercadoria_pre_devolucao+m.frete_cobrado_elegivel ORDER BY m.numero_pedido;",
25: "SELECT p.numero_pedido,c.saldo_financeiro,c.total_esperado,c.diferenca FROM vw_pagamentos_conciliacao c JOIN pedidos p USING(pedido_id) ORDER BY p.numero_pedido;",
26: "SELECT c.codigo,c.nome,count(p.pedido_id) pedidos,count(p.pedido_id) FILTER(WHERE p.status_logistico='CANCELADO') pedidos_cancelados,100::numeric*count(p.pedido_id) FILTER(WHERE p.status_logistico='CANCELADO')/nullif(count(p.pedido_id),0) taxa_cancelamento_pct FROM canais c LEFT JOIN pedidos p USING(canal_id) GROUP BY c.canal_id,c.codigo,c.nome ORDER BY c.codigo;",
27: "WITH x AS (SELECT cliente_id,count(*) compras FROM pedidos WHERE cliente_id IS NOT NULL AND status_logistico<>'CANCELADO' GROUP BY cliente_id) SELECT CASE WHEN compras=1 THEN 'uma' WHEN compras=2 THEN 'duas' ELSE 'tres_ou_mais' END faixa,count(*) clientes FROM x GROUP BY 1 ORDER BY CASE CASE WHEN compras=1 THEN 'uma' WHEN compras=2 THEN 'duas' ELSE 'tres_ou_mais' END WHEN 'uma' THEN 1 WHEN 'duas' THEN 2 ELSE 3 END;",
28: "WITH x AS (SELECT cliente_id,count(*) compras FROM pedidos WHERE cliente_id IS NOT NULL AND status_logistico<>'CANCELADO' GROUP BY cliente_id), t AS (SELECT count(*) compradores_identificados,count(*) FILTER(WHERE compras>=2) compradores_recorrentes FROM x) SELECT compradores_identificados,compradores_recorrentes,100::numeric*compradores_recorrentes/nullif(compradores_identificados,0) taxa_recompra_pct,round(100::numeric*compradores_recorrentes/nullif(compradores_identificados,0),2) taxa_recompra_pct_apresentacao FROM t;",
29: "WITH x AS (SELECT c.cliente_id,c.codigo_cliente,max(p.data_pedido) ultima_compra FROM clientes c JOIN pedidos p USING(cliente_id) WHERE p.status_logistico<>'CANCELADO' GROUP BY c.cliente_id,c.codigo_cliente) SELECT codigo_cliente,(ultima_compra AT TIME ZONE 'America/Sao_Paulo')::date ultima_compra_civil,DATE '2025-12-31'-(ultima_compra AT TIME ZONE 'America/Sao_Paulo')::date dias_civis_sem_compra FROM x WHERE ultima_compra<TIMESTAMPTZ '2025-10-03 03:00:00+00' ORDER BY ultima_compra,cliente_id;",
30: "WITH x AS (SELECT cliente_id,data_pedido,pedido_id,row_number() over(partition by cliente_id order by data_pedido,pedido_id) rn FROM pedidos WHERE cliente_id IS NOT NULL AND status_logistico<>'CANCELADO'), y AS (SELECT cliente_id,max(data_pedido) FILTER(WHERE rn=1) primeira_compra,max(data_pedido) FILTER(WHERE rn=2) segunda_compra FROM x GROUP BY cliente_id) SELECT avg((segunda_compra AT TIME ZONE 'America/Sao_Paulo')::date-(primeira_compra AT TIME ZONE 'America/Sao_Paulo')::date) intervalo_medio_dias FROM y WHERE segunda_compra IS NOT NULL;",
31: "SELECT c.categoria_id,c.nome categoria,coalesce(sum(v.quantidade_devolvida_concluida),0) unidades_devolvidas FROM categorias c LEFT JOIN produtos r USING(categoria_id) LEFT JOIN vw_itens_venda v ON v.produto_id=r.produto_id AND v.elegivel GROUP BY c.categoria_id,c.nome ORDER BY unidades_devolvidas DESC,c.nome;",
32: "SELECT r.produto_id,r.sku,coalesce(sum(v.quantidade) FILTER(WHERE v.elegivel),0) unidades_vendidas,coalesce(sum(v.quantidade_devolvida_concluida) FILTER(WHERE v.elegivel),0) unidades_devolvidas,100.0*sum(v.quantidade_devolvida_concluida) FILTER(WHERE v.elegivel)/nullif(sum(v.quantidade) FILTER(WHERE v.elegivel),0) taxa_devolucao_pct FROM produtos r LEFT JOIN vw_itens_venda v USING(produto_id) GROUP BY r.produto_id,r.sku ORDER BY taxa_devolucao_pct DESC NULLS LAST,r.sku;",
33: "SELECT date_trunc('month',p.data_pedido AT TIME ZONE 'America/Sao_Paulo')::date mes,sum(v.receita_mercadoria_pos_devolucao) receita_mercadoria_pos_devolucao FROM vw_itens_venda v JOIN pedidos p USING(pedido_id) WHERE v.elegivel GROUP BY 1 ORDER BY 1;",
34: "SELECT date_trunc('month',d.data_encerramento AT TIME ZONE 'America/Sao_Paulo')::date mes,sum(i.valor_reembolso) reembolso_concluido FROM devolucoes d JOIN itens_devolucao i USING(devolucao_id) WHERE d.status='CONCLUIDA' GROUP BY 1 ORDER BY 1;",
35: "SELECT r.sku,coalesce(sum(v.receita_mercadoria_pos_devolucao) FILTER(WHERE v.elegivel AND (p.data_pedido AT TIME ZONE 'America/Sao_Paulo')::date BETWEEN DATE '2023-01-01' AND DATE '2025-12-31'),0) receita_mercadoria_pos_devolucao,coalesce(sum(v.custo_mercadoria_mantida) FILTER(WHERE v.elegivel AND (p.data_pedido AT TIME ZONE 'America/Sao_Paulo')::date BETWEEN DATE '2023-01-01' AND DATE '2025-12-31'),0) custo_mercadoria_mantida,coalesce(sum(v.margem_mercadoria) FILTER(WHERE v.elegivel AND (p.data_pedido AT TIME ZONE 'America/Sao_Paulo')::date BETWEEN DATE '2023-01-01' AND DATE '2025-12-31'),0) margem_mercadoria,count(*) FILTER(WHERE v.elegivel AND (p.data_pedido AT TIME ZONE 'America/Sao_Paulo')::date BETWEEN DATE '2023-01-01' AND DATE '2025-12-31' AND v.preco_unitario-v.desconto_unitario-v.custo_unitario<0) quantidade_linhas_margem_unitaria_negativa,coalesce(sum(v.quantidade*(v.preco_unitario-v.desconto_unitario-v.custo_unitario)) FILTER(WHERE v.elegivel AND (p.data_pedido AT TIME ZONE 'America/Sao_Paulo')::date BETWEEN DATE '2023-01-01' AND DATE '2025-12-31' AND v.preco_unitario-v.desconto_unitario-v.custo_unitario<0),0) valor_margem_original_negativa FROM produtos r LEFT JOIN vw_itens_venda v USING(produto_id) LEFT JOIN pedidos p ON p.pedido_id=v.pedido_id GROUP BY r.produto_id,r.sku ORDER BY margem_mercadoria DESC,r.sku;",
36: "WITH x AS (SELECT c.categoria_id,c.nome categoria,r.produto_id,r.sku,coalesce(sum(v.receita_mercadoria_pre_devolucao) FILTER(WHERE v.elegivel),0) receita FROM categorias c JOIN produtos r USING(categoria_id) LEFT JOIN vw_itens_venda v USING(produto_id) GROUP BY c.categoria_id,c.nome,r.produto_id,r.sku) SELECT *,dense_rank() over(partition by categoria_id order by receita DESC) posicao FROM x ORDER BY categoria_id,posicao,receita DESC,sku;",
37: "WITH m AS (SELECT generate_series(DATE '2023-01-01',DATE '2025-12-01','1 month')::date mes),x AS (SELECT m.mes,coalesce(sum(v.receita_mercadoria_pre_devolucao) FILTER(WHERE v.elegivel),0) receita FROM m LEFT JOIN pedidos p ON date_trunc('month',p.data_pedido AT TIME ZONE 'America/Sao_Paulo')::date=m.mes LEFT JOIN vw_itens_venda v USING(pedido_id) GROUP BY 1),y AS (SELECT *,lag(receita,12) over(order by mes) receita_ano_anterior FROM x) SELECT *,receita-receita_ano_anterior variacao_abs,100*(receita-receita_ano_anterior)/nullif(receita_ano_anterior,0) taxa_variacao_pct FROM y ORDER BY mes;",
38: "WITH m AS (SELECT generate_series(DATE '2023-01-01',DATE '2025-12-01','1 month')::date mes),x AS (SELECT m.mes,coalesce(sum(v.receita_mercadoria_pre_devolucao) FILTER(WHERE v.elegivel),0) receita FROM m LEFT JOIN pedidos p ON date_trunc('month',p.data_pedido AT TIME ZONE 'America/Sao_Paulo')::date=m.mes LEFT JOIN vw_itens_venda v USING(pedido_id) GROUP BY 1) SELECT mes,receita,avg(receita) over(order by mes rows between 2 preceding and current row) media_movel_3m,count(*) over(order by mes rows between 2 preceding and current row) meses_na_janela FROM x ORDER BY mes;",
39: "WITH meses AS (SELECT generate_series(DATE '2023-01-01',DATE '2025-12-01','1 month')::date mes), classificado AS (SELECT p.pedido_id,date_trunc('month',p.data_pedido AT TIME ZONE 'America/Sao_Paulo')::date mes,case when p.cliente_id is null then 'convidado' when row_number() over(partition by p.cliente_id order by p.data_pedido,p.pedido_id)=1 then 'primeira_compra' else 'recorrente' end estagio FROM pedidos p WHERE p.status_logistico<>'CANCELADO'), valores AS (SELECT c.mes,c.estagio,m.receita_mercadoria_pre_devolucao receita FROM classificado c JOIN vw_pedidos_metricas m USING(pedido_id)), a AS (SELECT mes,coalesce(sum(receita) FILTER(WHERE estagio='convidado'),0) receita_convidado,coalesce(sum(receita) FILTER(WHERE estagio='primeira_compra'),0) receita_primeira_compra,coalesce(sum(receita) FILTER(WHERE estagio='recorrente'),0) receita_recorrente FROM valores GROUP BY mes) SELECT m.mes,coalesce(a.receita_convidado,0) receita_convidado,coalesce(a.receita_primeira_compra,0) receita_primeira_compra,coalesce(a.receita_recorrente,0) receita_recorrente,coalesce(a.receita_convidado,0)+coalesce(a.receita_primeira_compra,0)+coalesce(a.receita_recorrente,0) receita_total,100*coalesce(a.receita_convidado,0)/nullif(coalesce(a.receita_convidado,0)+coalesce(a.receita_primeira_compra,0)+coalesce(a.receita_recorrente,0),0) pct_convidado,100*coalesce(a.receita_primeira_compra,0)/nullif(coalesce(a.receita_convidado,0)+coalesce(a.receita_primeira_compra,0)+coalesce(a.receita_recorrente,0),0) pct_primeira_compra,100*coalesce(a.receita_recorrente,0)/nullif(coalesce(a.receita_convidado,0)+coalesce(a.receita_primeira_compra,0)+coalesce(a.receita_recorrente,0),0) pct_recorrente FROM meses m LEFT JOIN a USING(mes) ORDER BY m.mes;",
40: "WITH atual AS (SELECT date_trunc('month',p.data_pedido AT TIME ZONE 'America/Sao_Paulo')::date mes,p.canal_id,r.categoria_id,sum(v.receita_mercadoria_pos_devolucao) receita,sum(v.margem_mercadoria) margem,sum(v.quantidade) unidades FROM vw_itens_venda v JOIN pedidos p USING(pedido_id) JOIN produtos r USING(produto_id) WHERE v.elegivel GROUP BY 1,2,3), candidatos AS (SELECT a.*,b.receita receita_anterior,b.margem margem_anterior,b.unidades unidades_anteriores FROM atual a JOIN atual b ON b.canal_id=a.canal_id AND b.categoria_id=a.categoria_id AND b.mes=a.mes-interval '1 year' WHERE a.mes>=DATE '2024-01-01' AND a.unidades>0 AND b.unidades>0 AND a.receita<b.receita AND a.margem<b.margem) SELECT x.mes,c.codigo canal,ca.nome categoria,x.receita,x.receita_anterior,x.margem,x.margem_anterior,x.receita_anterior-x.receita queda_receita_abs,x.margem_anterior-x.margem queda_margem_abs,100*(x.receita_anterior-x.receita)/nullif(x.receita_anterior,0) queda_receita_pct,100*(x.margem_anterior-x.margem)/nullif(x.margem_anterior,0) queda_margem_pct,(x.receita_anterior-x.receita)+(x.margem_anterior-x.margem) score_investigacao FROM candidatos x JOIN canais c USING(canal_id) JOIN categorias ca USING(categoria_id) ORDER BY score_investigacao DESC,queda_receita_abs DESC,queda_margem_abs DESC,x.mes,c.codigo,ca.nome LIMIT 20;",
}
for i in range(1, 41):
    (P / f"q{i:02d}.sql").write_text("SET TIME ZONE 'UTC';\n" + q[i] + "\n", encoding="utf-8")
